

name: Deploy dev
permissions:
  security-events: write


on:

  push:
    branches: [ "dev" ]

jobs:
  # This workflow contains a single job called "build"
  checkout:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: View Contents
        run: ls -l

      - uses: actions/upload-artifact@master
        with:
          name: checkout-artifact
          path: ./

  terraform_validate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: checkout
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/download-artifact@master
        with:
          name: checkout-artifact
          path: ./

      - name: View Contents
        run: ls -l

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7 

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "dynamic_env"
          replace: "dev"
          regex: false
          include: "backend.tf"    

      - name: Terraform Init
        id: init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Change File Permission
        run: chmod -R 777 .terraform/

      - uses: actions/upload-artifact@master
        with:
          name: checkout-artifact
          path: ./  

  terraform_plan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [terraform_validate]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/download-artifact@master
        with:
          name: checkout-artifact
          path: ./

      - name: View Contents
        run: ls -l

      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file=config/dev/terraform.tfvars -out=dev-plan.out
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - uses: actions/upload-artifact@master
        with:
          name: checkout-artifact
          path: ./

  terraform_apply:
     # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [terraform_plan]
    environment: dev

     # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/download-artifact@master
        with:
          name: checkout-artifact
          path: ./
  
      - name: View Contents
        run: ls -l

      - name: Terraform Apply
        id: apply
        run: terraform apply dev-plan.out --auto-approve
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
