name: Remote update execution
permissions:
  security-events: write
on:
  push:
    branches: [ "uat" ]
    paths: ['app/**']
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
                    cd /home/deploy/git/gpoc/
                    git pull origin dev
                    cp -R app/* /var/www/html/wp-content/themes/twentytwentythree/