 # This is a basic workflow to help you get started with Actions

name: Destroy POC

# Controls when the workflow will run
on:
   #Triggers the workflow on push or pull request events but only for the "main" branch
  schedule: ## Schedule the job to run at xx weekly
    #- cron: '*/5 * * * *'
    - cron: '0 0 1 1 *'

jobs:
   #This workflow contains a single job called "build"
  checkout:
     #The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: POC
     #Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       #Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: View Contents
        run: ls -l

      - uses: actions/upload-artifact@master
        with:
          name: checkout-artifact
          path: ./

  terraform_validate:
     #The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: checkout
    defaults:
      run:
        working-directory: POC
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/download-artifact@master
        with:
          name: checkout-artifact
          path: ./

      - name: View Contents
        run: ls -l

      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_subcommand: init
          tf_actions_version: 0.12.13
          tf_actions_working_dir: 'POC'
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_subcommand: validate
          tf_actions_version: 0.12.13
          tf_actions_working_dir: 'POC'

  terraform_plan:
     # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: terraform_validate
    defaults:
      run:
        working-directory: POC
     # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/download-artifact@master
        with:
          name: checkout-artifact
          path: ./

      - name: View Contents
        run: ls -l

      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_subcommand: init
          tf_actions_version: 0.12.13
          tf_actions_working_dir: 'POC'
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Plan
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_subcommand: plan
          tf_actions_version: 0.12.13
          tf_actions_working_dir: 'POC'
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}        

  terraform_destroy:
      #The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [terraform_validate]
    defaults:
      run:
        working-directory: POC
      #Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/download-artifact@master
        with:
          name: checkout-artifact
          path: ./

      - name: View Contents
        run: ls -l

      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_subcommand: init
          tf_actions_version: 0.12.13
          tf_actions_working_dir: 'POC'
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Destroy
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_subcommand: 'destroy'
          tf_actions_version: 0.12.13
          tf_actions_working_dir: 'POC'
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }} 